[build]
  base = "front/"
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "https://otworks.netlify.app/"
  to = "https://otworks.netlify.app/en"
  status = 302
  force = false
  conditions = {Language = ["en"]}

[[redirects]]
  from = "https://otworks.netlify.app/*"
  to = "https://otworks.netlify.app/en/:splat"
  status = 302
  force = true
  conditions = {Language = ["en"]}